CountFreq/CountFreq/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from freqApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^$',views.BasePage,name='basepage'),
    url('^frequency/',include('freqApp.urls')),
]

CountFreq/freqApp/urls.py
from django.conf.urls import url
from freqApp import views

app_name = 'freqApp'

urlpatterns =[

    url('^$',views.FrequencyPage,name='frequencypage'),
    url('^results/$',views.ResultsPage,name='resultspage'),

]

CountFreq/freqApp/models.py
from django.db import models

# Create your models here.
class UsedURL(models.Model):

    url = models.CharField(max_length=500)

    word1 =  models.CharField(max_length=100)

    word1count = models.IntegerField()

    word2 = models.CharField(max_length=100)

    word2count = models.IntegerField()

    word3 = models.CharField(max_length=100)

    word3count = models.IntegerField()

    word4 =  models.CharField(max_length=100)

    word4count = models.IntegerField()

    word5 = models.CharField(max_length=100)

    word5count = models.IntegerField()

    word6 = models.CharField(max_length=100)

    word6count = models.IntegerField()

    word7 =  models.CharField(max_length=100)

    word7count = models.IntegerField()

    word8 = models.CharField(max_length=100)

    word8count = models.IntegerField()

    word9 = models.CharField(max_length=100)

    word9count = models.IntegerField()

    word10 = models.CharField(max_length=100)

    word10count = models.IntegerField()

    def __str__(self):

        return self.url

CountFreq/freqApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import trafilatura
from collections import Counter
from operator import itemgetter
from freqApp.models import UsedURL
import string



# Create your views here.
def BasePage(request):

    return render(request,'freqApp/BasePage.html')

def FrequencyPage(request):

    return render(request,'freqApp/FrequencyPage.html')

def ResultsPage(request):

    cond = False

    url =''
    text=''

    word_pair=[]

    blacklist = []

    used_url = UsedURL()

    if request.method == 'POST':
        used_url = UsedURL()
        url = request.POST.get('url')

        if UsedURL.objects.filter(url = url).count() <= 0 and (UsedURL.objects.count() >= 0):

            down = trafilatura.fetch_url(url)
            temp_text = trafilatura.extract(down)

            punc = string.punctuation

            punc = list(punc)

            punc.append('')
            punc.append('--')

            for alpha in temp_text:

                if alpha in punc:
                    pass
                else:
                    text += alpha

            text = text.split(' ')
            unique_words = sorted(set(text))

            unique_words = [x.lower() for x in unique_words]

            unique_words = sorted(set(unique_words))

            fp = open('1-1000.txt','r')

            for line in fp:

                blacklist.append(line[:len(line)-1])

            fp.close()

            for word in unique_words:

                if word not in blacklist:
                    word_pair.append((word,text.count(word)))

            word_pair = sorted(word_pair,key=itemgetter(1), reverse=True)


            used_url = UsedURL.objects.create(url = url,

            word1 = word_pair[0][0],
            word1count = word_pair[0][1],
            word2 = word_pair[1][0],
            word2count = word_pair[1][1],
            word3 = word_pair[2][0],
            word3count = word_pair[2][1],
            word4 = word_pair[3][0],
            word4count = word_pair[3][1],
            word5 = word_pair[4][0],
            word5count = word_pair[4][1],
            word6 = word_pair[5][0],
            word6count = word_pair[5][1],
            word7 = word_pair[6][0],
            word7count = word_pair[6][1],
            word8 = word_pair[7][0],
            word8count = word_pair[7][1],
            word9 = word_pair[8][0],
            word9count = word_pair[8][1],
            word10 = word_pair[9][0],
            word10count = word_pair[9][1],


            )

            used_url.save()

        else:
            cond = True
            for obj in UsedURL.objects.all():

                if obj.url == url:
                    print(obj.url)
                    break

            return render(request,'freqApp/ResultsPage.html',{'url':obj,'message':'Hi There! You have already checked this URL'})

    return render(request,'freqApp/ResultsPage.html',{'url':used_url,'message':'Thank you for using this App!'})

CountFreq/templates/freqApp/BasePage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ATG Task</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </head>
  <body style=" background-image: url('https://wallpapercave.com/wp/wp6850123.jpg'); " >
    <div class="container">
      <div class="jumbotron" style=" background-image: url('https://i.pinimg.com/originals/3a/8d/47/3a8d47cbd0acca4986bf0d6ca2ab3be3.jpg'); border-radius: 40px;" >
      {% block bodyblock %}


                  <h1 style=" text-align: center; color: white;" >Word Frequency Counter</h1>
                  <div style=" border-radius: 40px; background-color: rgba(534, 512, 125, 0.5); " class="card">
                    <div class="card-header">
                      Frequency Task
                    </div>
                    <div class="card-body">
                      <h5 style=" text-align: center;" class="card-title">
                        Welcome to Word Frequency Counter Task! <br> <br>
                        Count what? <br> <br>
                        Well, on this site, you can paste any url you desire <br>
                        and it will return you with <br> the top 10 most occuring words on that <br>
                        particular web page.

                      </h5>

                      <a style=" border-radius: 40px; position: relative; top:50%; left:45%; "  class="btn btn-success" href="{% url 'freqApp:frequencypage' %}">Click Me to Start!</a>

                    </div>
                  </div>







    {% endblock %}

  </div>
</div>

  </body>
</html>

CountFreq/templates/freqApp/FrequencyPage.html
<!DOCTYPE html>
{% extends 'freqApp/BasePage.html' %}

{% block bodyblock %}
<h2 style=" color: white;" > Paste A URL</h2>
<div class="jumbotron" style=" border-radius: 50px; background-color: rgba(654, 122, 212, 0.4); " >
  <form class="form-inline" action=" {% url 'freqApp:resultspage' %} "  method="POST">
      {% csrf_token %}
    <div class="form-group mb-2">
      <label style=" color: white;" for="">Paste a URL Here</label>
    </div>
    <div class="form-group mx-sm-3 mb-2">
      <input type="url" style=" width: 500px; "  name="url" class="form-control" id="inputPassword2" placeholder="URL">
    </div>
    <br>
      <input type="submit" class="btn btn-dark" style=" border-radius: 50px;"  name="" value="Count Frequency">
  </form>
</div>




{% endblock %}

CountFreq/templates/freqApp/ResultsPage.html
<!DOCTYPE html>
{% extends 'freqApp/BasePage.html' %}

{% block bodyblock %}


  <div class="media" style=" text-align: center; background-color: rgba(420, 450, 264, 0.5); " >
  <img src="https://files.realpython.com/media/Three-Ways-of-Storing-and-Accessing-Lots-of-Images-in-Python_Watermarked.e0e46e94536c.jpg" style=" border-radius: 50px; width:254px; height:100px; " class="mr-3" alt="...">
  <div class="media-body">
    <h3 class="mt-0"> <strong> {{ message }} <br> <br> The Results are Below: </strong> </h3>

  </div>
</div>

      <div class="jumbotron" style=" font-size: 30px;" >
        <div class="row">
          <div class="col-sm">
          TOP 10 WORDS
          </div>
          <div class="col-sm">
          WORD COUNT
          </div>
        </div>
      <div class="row">
        <div class="col-sm">
        {{ url.word1 }}
        </div>
        <div class="col-sm">
        {{url.word1count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
        {{url.word2}}
        </div>
        <div class="col-sm">
         {{ url.word2count }}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
        {{url.word3}}
        </div>
        <div class="col-sm">
        {{url.word3count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
        {{url.word4}}
        </div>
        <div class="col-sm">
          {{url.word4count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
        {{url.word5}}
        </div>
        <div class="col-sm">
        {{url.word5count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          {{url.word6}}
        </div>
        <div class="col-sm">
        {{ url.word6count }}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          {{url.word7}}
        </div>
        <div class="col-sm">
          {{url.word7count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          {{url.word8}}
        </div>
        <div class="col-sm">
          {{url.word8count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          {{url.word9}}
        </div>
        <div class="col-sm">
          {{url.word9count}}
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          {{url.word10}}
        </div>
        <div class="col-sm">
          {{url.word10count}}
        </div>
      </div>
      </div>
      <a class="btn btn-danger" href="{% url 'freqApp:frequencypage' %}">Check Some More!</a>
      <a class="btn btn-warning" href="{% url 'basepage' %}">Go Back Home!</a><br><br>

{% endblock %}